### PR TITLE
BREAKING: Drop support for nodejs 8 and EOL non-LTS versions

### PR DESCRIPTION
**Pull request by legobeat**
- Remove support for nodejs 8
- Remove support for EOL non-LTS versions (9, 11, 13, 15, 17, 19)
- Minor versions chosen to preserve compatibility with nodejs versions available in distro repos for:
  - Debian (down to 10/buster)
  - Ubuntu (down to 20.04 LTS/focal)
  - RHEL (down to 8)
- Matches dependency ranges in using `@metamask/ethjs-` packages
- ci: remove Node.js v8 from build/test matrix
- ci: add new and supported Node.js majors to build/test matrix

### CODE REVIEW

**Review by mikesposito — APPROVED** [review]

**Review by mikesposito — CHANGES_REQUESTED** [review]
We should remove v8 from the CI matrix

**Comment by legobeat** [comment]
> We should remove v8 from the CI matrix

Done. Also added newer and supported majors to build+test.

**Comment by mikesposito** [comment]
Looks like CI has become unhappy

**Comment by legobeat** [comment]
Pinning npm to v6 to get consistent lockfile across node version (can upgrade to lockfile v2 and npm7)

**Review by mcmire — APPROVED** [review]
LGTM.

**Pull request merged**
